# Rest Client Extension -- Vs code 



# GET http://localhost:3000/users/showall


# GET https://userapi.azurewebsites.net/



# GET https://userapi.cyclic.app/users/showall


# GET https://userapi.azurewebsites.net/users/showall


# POST http://localhost:3000/users/login HTTP/1.1
POST https://userapi.cyclic.app/users/login HTTP/1.1
content-type: application/json

{
    "email": "anshusharma6327@gmail.com",
    "password": "1233456"
}